server:
  port: 9001
spring:
  application:
    name: tensquare-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://118.126.65.84:3306/tensquare_base?characterEncoding=utf-8
    username: root
    password: 134567
  jpa:
    database: mysql
    show-sql: true